name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  init-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npx eslint .

      - name: Build test Docker image
        run: docker build -f Dockerfiles/test.Dockerfile -t test-image .

      - name: Build user Docker image
        run: docker build -f Dockerfiles/user.Dockerfile -t user-image .